# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MapApp' do
 pod 'GoogleMaps'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MapApp


end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end
